name: pule
description: "Pule - A cross-platform prayer list app"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  share_plus: ^10.1.4
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  uuid: ^4.5.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  fake_cloud_firestore: ^3.1.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
